name: notification_notes
description: Notification notes app

version: 1.0.3

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.3
  shared_preferences: ^0.5.12+4
  flutter_local_notifications: 0.9.1
  flutter_slidable: ^0.5.7

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
